version: '2'
services:
  app:
    depends_on:
      - database
    build:
      context: ./
      dockerfile: docker/app/app.dockerfile
      args:
        - USER_ID=1001
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
  web:
    depends_on:
      - app
    build:
      context: ./
      dockerfile: docker/web/web.dockerfile
    working_dir: /var/www/html
    volumes_from:
      - app
    ports:
      - 8080:80
  database:
    image: mysql:5.7
    volumes:
      - $HOME/.test-docker/databases/davicervo:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=homestade
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
